### ISSUE TITLE
Joshua Koran: Broader CfC

### ISSUE THREAD

**Issue by ekr** [patcg/patwg-charter#13]
Note: I am transcribing comments from the gdoc to issues.

Joshua Koran writes:
> I think this is a great idea to get feedback from folks who may not be able to always attend
>
> Has it been considered to extend this process to get feedback from other stakeholders who may not be able to participate in the Working Group (e.g., if small publishers were to be under represented in this WG), extending the survey to such a wider community in the W3C and even beyond could be incorporated earlier in the process

**Comment by AramZS** [comment]
I think it is a good idea to use the relationship between the WG and the CG to extend a timeboxed period for feedback from the larger community, since I agree that there are stakeholders who are both less technical and less likely to get involved on the repo of specs but who are likely to have useful feedback. I'll put in a PR.
