### ISSUE TITLE
Where do we propose to advance to, CR or PR?

### ISSUE THREAD

**Issue by ekr** [patcg/patwg-charter#9]
The charter seems to be confused as to whether we are going to try to go to PR or whether we are going to stop at PR.

**Comment by AramZS** [comment]
I think we should be clear that we want to advance towards RECs, since that's the usual goal of Working Groups? We should aim to adhere to [the new Living Standards process](https://www.w3.org/2020/Talks/TPAC/W3C2020/) for moving towards RECs and keeping them up to date in the form of [Evergreen Recommendations](https://www.w3.org/wiki/Evergreen_Standards) under the living standards process. What do you think is the best way to make this clear in the document @ekr ?

**Comment by AramZS** [comment]
I would like to have a pull request to cover this ready for our meeting, but I'm not well-versed enough with W3C language to know how to make this clearer than it currently is. Would someone either advise or open a PR?

**Comment by ekr** [comment]
I tend to prefer the "Living Standards (CR Forever)" Variant on slide 8. My experience is that there isn't a lot of value in the multi-step process, except for really requiring multiple implementations, which we should just do at the stage of taking things to CR.

**Comment by seanturner** [comment]
I put in some text to at least align the current text in the deliverables and the success section.

I tend to agree with ekr that when we get to CR we should probably already have two implementations so I left that expectation in.

**Comment by seanturner** [comment]
Approved in principal. Jeffrey to provide some additional wording about the CR state.
